services:
  navidrome:
    container_name: "navidrome"
    env_file: ".env"
    image: deluan/navidrome:latest
    restart: unless-stopped
    networks:
      - nginx
    volumes:
      - "./data:/data"
      - "/mnt/samba/audio/flac:/music:ro"

networks:
  nginx:
    external: true
    name: nginx
